site_name: PyClasher
repo_url: https://github.com/201st-Luka/PyClasher
repo_name: 201st-Luka/PyClasher
copyright: Copyright &copy; 2023 - Present 201st-Luka
docs_dir: docs/src
edit_uri: edit/stable/docs/src
site_url: https://201st-Luka.github.io/pyclasher/

theme:
  name: material
  favicon: images/favicon.png
  #  custom_dir: docs/overrides
  features:
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.share
    - navigation.indexes
    - navigation.prune
    - toc.follow
    - content.tooltips
    - content.code.annotate
    - content.action.edit
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github-alt

  logo: images/logo-minified.svg
  font:
    code: Roboto Mono

watch:
  - pyclasher


extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/j2PAF9Wru8
      name: Discord
    - icon: fontawesome/brands/github
      link: https://github.com/201st-Luka/PyClasher
      name: Github Repository

extra_css:
  - extra.css

extra_javascript:
  - scripts/feedback.js

plugins:
  - search
  - awesome-pages
  - autorefs
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
  - git-committers:
      repository: 201st-Luka/PyClasher
      branch: master
  - mkdocstrings:
      #    custom_templates: docs/templates
      enable_inventory: true
      handlers:
        python:
          selection:
            inherited_members: True
            filters:
              - "!^_"
          rendering:
            members_order: source
            show_bases: True
            show_root_toc_entry: False
            group_by_category: True
            heading_level: 3
            show_if_no_docstring: True
  - minify:
      minify_html: true
  # keep this at the bottom of the plugins list - if you are building without insiders, comment it out
  - privacy:
      # Downloads all external resources and stores them locally
      externals: bundle
      enabled: !ENV [ DEPLOY, False ]


markdown_extensions:
  - meta
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs/_snippets
      check_paths: True
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 6
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - attr_list
  - md_in_html