from os import environ


CLASH_OF_CLANS_LOGIN_EMAIL = environ["CLASH_OF_CLANS_LOGIN_EMAIL"]

CLASH_OF_CLANS_LOGIN_PASSWORD = environ["CLASH_OF_CLANS_LOGIN_PASSWORD"]

TEST_CLAN_TAG = environ["TEST_CLAN_TAG"]

TEST_PLAYER_TAG = environ["TEST_PLAYER_TAG"]

TEST_CLAN_NAME = environ["TEST_CLAN_NAME"]
