from os import environ


CLASH_OF_CLANS_LOGIN_EMAIL = environ.get("CLASH_OF_CLANS_LOGIN_EMAIL")

CLASH_OF_CLANS_LOGIN_PASSWORD = environ.get("CLASH_OF_CLANS_LOGIN_PASSWORD")

TEST_CLAN_TAG = environ.get("TEST_CLAN_TAG")

TEST_PLAYER_TAG = environ.get("TEST_PLAYER_TAG")

TEST_CLAN_NAME = environ.get("TEST_CLAN_NAME")
