name: create pre-release

on:
  pull_request:
    types:
      - closed
    branches:
      - pre-releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel

      - name: Get package version
        id: get_version
        run: |
          import re
          with open('setup.py') as setup_py:
              content = setup_py.read()
              version = re.search(r"VERSION = '([^']+)'", content).group(1)
          echo "::set-output name=version::$version"

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Create Pre-release
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const github = context.github;
            const version = "${{ steps.get_version.outputs.version }}";
            const response = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${version}`,
              name: `Pre-release ${version}`,
              body: "Changelog",
              draft: true,
              prerelease: true
            });
            console.log(response.data.html_url);

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            ./dist/*.whl
            ./dist/*.tar.gz