name: pre pull-request

on:
  [pull_request]

jobs:
  testing:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-tests.txt
    - name: Test with pytest
      env:
        CLASH_OF_CLANS_LOGIN_EMAIL: ${{ secrets.CLASH_OF_CLANS_LOGIN_EMAIL }}
        CLASH_OF_CLANS_LOGIN_PASSWORD: ${{ secrets.CLASH_OF_CLANS_LOGIN_PASSWORD }}
        TEST_CLAN_TAG: ${{ vars.TEST_CLAN_TAG }}
        TEST_PLAYER_TAG: ${{ vars.TEST_PLAYER_TAG }}
        TEST_CLAN_NAME: ${{ vars.TEST_CLAN_NAME }}
      run: pytest